# Generated by Django 3.2.25 on 2025-12-09 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование кометы')),
                ('description', models.TextField(verbose_name='Описание расчёта')),
                ('price', models.PositiveIntegerField(verbose_name='Цена расчёта, ₽')),
                ('image_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ключ изображения в MinIO')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалена')),
                ('k_x', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Коэффициент k_x (а.е.)')),
                ('k_y', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Коэффициент k_y (а.е.)')),
                ('k_z', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Коэффициент k_z (а.е.)')),
            ],
            options={
                'verbose_name': 'Комета',
                'verbose_name_plural': 'Кометы',
            },
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удалён'), ('formed', 'Сформирован'), ('completed', 'Завершён'), ('rejected', 'Отклонён')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('formed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('telescopes_list', models.JSONField(default=services.models.default_telescopes_list, verbose_name='Список телескопов')),
                ('total_distance_au', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Общее расстояние, а.е.')),
                ('astronomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_distances', to=settings.AUTH_USER_MODEL, verbose_name='Астроном')),
                ('chief_astronomer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chief_astronomer_distances', to=settings.AUTH_USER_MODEL, verbose_name='Главный астроном')),
            ],
            options={
                'verbose_name': 'Расчёт расстояния',
                'verbose_name_plural': 'Расчёты расстояний',
            },
        ),
        migrations.CreateModel(
            name='RequestComet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('coords_x', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Координата X')),
                ('coords_y', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Координата Y')),
                ('coords_z', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Координата Z')),
                ('comet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.comet')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_comets', to='services.distance')),
            ],
            options={
                'verbose_name': 'Комета в заявке',
                'verbose_name_plural': 'Кометы в заявках',
                'unique_together': {('request', 'comet')},
            },
        ),
        migrations.AddConstraint(
            model_name='distance',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('astronomer',), name='unique_draft_per_astronomer'),
        ),
    ]
