# Generated by Django 5.2.5 on 2025-09-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comet',
            name='non_grav_params',
        ),
        migrations.AddField(
            model_name='comet',
            name='k_x',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Коэффициент k_x (а.е.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comet',
            name='k_y',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Коэффициент k_y (а.е.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comet',
            name='k_z',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Коэффициент k_z (а.е.)'),
            preserve_default=False,
        ),
    ]
