# Generated by Django 3.2.25 on 2025-12-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distance',
            name='total_distance_au',
        ),
        migrations.AddField(
            model_name='requestcomet',
            name='distance_au',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Расстояние от Солнца, а.е.'),
        ),
    ]
