# Generated by Django 5.2.5 on 2025-09-15 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_comet_non_grav_params_comet_k_x_comet_k_y_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Astronomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя астронома')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Астроном',
                'verbose_name_plural': 'Астрономы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Telescope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название телескопа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Телескоп',
                'verbose_name_plural': 'Телескопы',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='calculationrequest',
            name='astronomer_name',
        ),
        migrations.RemoveField(
            model_name='calculationrequest',
            name='telescope_name',
        ),
        migrations.AddField(
            model_name='calculationrequest',
            name='astronomer_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.astronomer', verbose_name='Астроном'),
        ),
        migrations.AddField(
            model_name='calculationrequest',
            name='telescope_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.telescope', verbose_name='Телескоп'),
        ),
    ]
