# Generated by Django 3.2.25 on 2025-12-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_add_customuser_only'),
        ('services', '0002_auto_20251210_0258'),
    ]

    operations = [
    ]
