# Generated by Django 5.2.5 on 2025-09-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_astronomer_telescope_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationrequest',
            name='astronomer_ref',
        ),
        migrations.RemoveField(
            model_name='calculationrequest',
            name='telescope_ref',
        ),
        migrations.AddField(
            model_name='calculationrequest',
            name='astronomer_name',
            field=models.CharField(default='Судьи В. Г.', max_length=100, verbose_name='Имя астронома'),
        ),
        migrations.AddField(
            model_name='calculationrequest',
            name='telescope_name',
            field=models.CharField(default='Хаббл', max_length=100, verbose_name='Название телескопа'),
        ),
        migrations.DeleteModel(
            name='Astronomer',
        ),
        migrations.DeleteModel(
            name='Telescope',
        ),
    ]
