# Generated by Django 5.2.5 on 2025-09-15 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_calculationrequest_astronomers_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationrequest',
            name='astronomer_name',
        ),
        migrations.RemoveField(
            model_name='calculationrequest',
            name='telescope_name',
        ),
    ]
