# Generated by Django 5.2.5 on 2025-10-13 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_remove_calculationrequest_astronomer_name_and_more"),
    ]

    operations = [
        # Переименовываем модель и таблицу
        migrations.RenameModel(
            old_name='CalculationRequest',
            new_name='Distance',
        ),
        
        # Переименовываем constraint
        migrations.RunSQL(
            "ALTER INDEX unique_draft_per_astronomer RENAME TO unique_draft_per_astronomer_new;",
            reverse_sql="ALTER INDEX unique_draft_per_astronomer_new RENAME TO unique_draft_per_astronomer;"
        ),
    ]